# -*- coding: utf-8 -*-
"""Untitled19.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yygnFXrXXhEkFSVSnYIjRxnLFjUR2bal
"""

# ===============================
# FAKE NEWS DETECTION SYSTEM
# ===============================

import streamlit as st
import pandas as pd
import numpy as np
import re
import requests
from bs4 import BeautifulSoup
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.metrics import accuracy_score
import joblib
import random

# -------------------------------
# APP CONFIGURATION
# -------------------------------
st.set_page_config(
    page_title="AI Fake News Detector",
    page_icon="📰",
    layout="wide"
)

st.markdown("""
<style>
.main-title { font-size: 2.5rem; font-weight: 800; text-align: center; color: #1F2937; margin-bottom: 1rem; }
.sample-box { background: #F3F4F6; padding: 1rem; border-radius: 10px; margin-bottom: 1rem; }
</style>
""", unsafe_allow_html=True)

st.markdown('<div class="main-title">📰 AI Fake News Detection System</div>', unsafe_allow_html=True)

# -------------------------------
# SYSTEM OVERVIEW
# -------------------------------
st.markdown("""
### System Overview
This AI-powered system detects whether a news headline or article is **fake or real** using machine learning models:
- **Naive Bayes**: Good for text classification with probabilistic inference.
- **Logistic Regression**: Provides robust linear classification based on text features.

You can **input a headline or a news article URL**, and the system will predict whether the content is likely fake or genuine.
""")

# -------------------------------
# SAMPLE DATA (for demonstration)
# -------------------------------
sample_texts = [
    "BREAKING!!! Government confirms secret cure for COVID-19, doctors shocked!",
    "Local library opens new reading program for children, community welcomes initiative.",
]

# -------------------------------
# MODEL TRAINING (Dummy Dataset)
# -------------------------------
# For demonstration, small dataset
data = {
    'text': [
        "BREAKING!!! Secret cure discovered for COVID-19!!!",
        "Government hides alien encounters from public",
        "Experts claim miracle weight loss pills work overnight",
        "Local library opens new reading program",
        "City council approves new park for community",
        "Scientists release study on climate change effects"
    ],
    'label': [1,1,1,0,0,0]  # 1=fake, 0=real
}

df = pd.DataFrame(data)

# Split dataset
X_train, X_test, y_train, y_test = train_test_split(df['text'], df['label'], test_size=0.2, random_state=42)

# Create pipelines
nb_pipeline = Pipeline([
    ('tfidf', TfidfVectorizer(stop_words='english')),
    ('clf', MultinomialNB())
])

lr_pipeline = Pipeline([
    ('tfidf', TfidfVectorizer(stop_words='english')),
    ('clf', LogisticRegression(max_iter=1000))
])

# Train models
nb_pipeline.fit(X_train, y_train)
lr_pipeline.fit(X_train, y_train)

# -------------------------------
# USER INPUT
# -------------------------------
input_option = st.radio("Select input type:", ["Headline/Text", "News URL"])

if input_option == "Headline/Text":
    user_input = st.text_area("Enter headline or news text:", height=120, placeholder="Paste a headline or text here...")
else:
    url_input = st.text_input("Enter full news article URL:")
    user_input = ""
    if url_input:
        try:
            r = requests.get(url_input, timeout=5)
            soup = BeautifulSoup(r.content, "html.parser")
            paragraphs = soup.find_all('p')
            user_input = " ".join([p.get_text() for p in paragraphs])
        except:
            st.error("❌ Could not fetch text from URL.")

# -------------------------------
# SAMPLE EXAMPLE
# -------------------------------
if st.button("Load Sample Fake News"):
    user_input = random.choice(sample_texts)

if user_input:
    st.markdown('<div class="sample-box"><strong>Input Text:</strong><br>' + user_input + '</div>', unsafe_allow_html=True)

    # -------------------------------
    # PREDICTION
    # -------------------------------
    nb_pred = nb_pipeline.predict([user_input])[0]
    nb_prob = nb_pipeline.predict_proba([user_input])[0][nb_pred]

    lr_pred = lr_pipeline.predict([user_input])[0]
    lr_prob = lr_pipeline.predict_proba([user_input])[0][lr_pred]

    # Display results
    st.markdown("### 🔎 Prediction Results")
    col1, col2 = st.columns(2)

    with col1:
        st.markdown(f"**Naive Bayes:** {'Fake' if nb_pred else 'Real'} ({nb_prob*100:.1f}% confidence)")
    with col2:
        st.markdown(f"**Logistic Regression:** {'Fake' if lr_pred else 'Real'} ({lr_prob*100:.1f}% confidence)")

    # Combined risk
    combined_score = (nb_pred + lr_pred) / 2
    if combined_score >= 0.5:
        st.warning("⚠️ The content is likely **FAKE NEWS**. Verify sources carefully!")
    else:
        st.success("✅ The content appears **REAL**. Always cross-check sources!")

# -------------------------------
# MODEL EVALUATION (optional for dev)
# -------------------------------
# accuracy_nb = accuracy_score(y_test, nb_pipeline.predict(X_test))
# accuracy_lr = accuracy_score(y_test, lr_pipeline.predict(X_test))
# st.info(f"Model Accuracy (dev only): Naive Bayes={accuracy_nb:.0%}, Logistic Regression={accuracy_lr:.0%}")