import streamlit as st
import pandas as pd
import numpy as np
from datetime import datetime

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.pipeline import Pipeline
from sklearn.model_selection import train_test_split

# ---------------- PAGE CONFIG ----------------
st.set_page_config(
    page_title="Fake News Detection System",
    layout="wide"
)

# ---------------- TRAINING DATA ----------------
data = {
    "text": [
        "Breaking news miracle cure discovered overnight",
        "Government announces new education policy today",
        "Shocking secret revealed about vaccines",
        "The prime minister met foreign leaders yesterday",
        "Experts warn phones will explode tonight",
        "Economic growth increased by three percent this year",
        "Celebrity claims salt water cures all diseases",
        "New tax regulation introduced for small businesses"
    ],
    "label": [1, 0, 1, 0, 1, 0, 1, 0]  # 1 = Fake, 0 = Genuine
}

df = pd.DataFrame(data)

# ---------------- MODEL TRAINING ----------------
@st.cache_resource
def train_model(dataframe):
    model = Pipeline([
        ("tfidf", TfidfVectorizer(
            lowercase=True,
            stop_words="english",
            ngram_range=(1, 2),
            min_df=1,
            max_df=0.9
        )),
        ("classifier", LogisticRegression(
            max_iter=2000,
            class_weight="balanced"
        ))
    ])

    X_train, X_test, y_train, y_test = train_test_split(
        dataframe["text"],
        dataframe["label"],
        test_size=0.2,
        random_state=42
    )

    model.fit(X_train, y_train)
    return model

model = train_model(df)

# ---------------- SESSION STATE ----------------
if "history" not in st.session_state:
    st.session_state.history = []

# ---------------- SIDEBAR ----------------
st.sidebar.title("📰 Fake News Detection System")
st.sidebar.subheader("System Overview")
st.sidebar.write("NLP based text classification")
st.sidebar.text("Model: TF-IDF + Logistic Regression")
st.sidebar.text("Prediction Type: Probabilistic")
st.sidebar.success("System Status: Operational")
st.sidebar.caption("Version 1.0 | 2026")

# ---------------- TABS ----------------
tab_home, tab_analyzer, tab_dashboard, tab_reports = st.tabs(
    ["Home", "Analyzer", "Dashboard", "Reports"]
)

# ---------------- HOME ----------------
with tab_home:
    st.header("Welcome")
    st.write(
        """
        This system detects **potential fake news** using
        Natural Language Processing and Machine Learning.

        The model analyzes linguistic patterns and produces
        confidence based predictions.
        """
    )

    st.info(
        "This system provides an early warning indicator and does not perform factual verification."
    )

# ---------------- ANALYZER ----------------
with tab_analyzer:
    st.header("🧠 News Analyzer")

    text_input = st.text_area(
        "Enter news text for analysis",
        height=180
    )

    if st.button("🔍 Analyze News"):
        if not text_input.strip():
            st.warning("Please enter text before analysis.")
        else:
            prediction = model.predict([text_input])[0]
            proba_fake, proba_genuine = model.predict_proba([text_input])[0]

            label = "Likely Fake News" if prediction == 1 else "Likely Genuine News"
            confidence = max(proba_fake, proba_genuine)

            col1, col2 = st.columns(2)
            with col1:
                st.metric("Prediction", label)
            with col2:
                st.metric("Confidence", f"{confidence * 100:.2f}%")

            st.progress(confidence)

            # ---------------- EXPLAINABILITY ----------------
            tfidf = model.named_steps["tfidf"]
            classifier = model.named_steps["classifier"]

            feature_names = tfidf.get_feature_names_out()
            coefficients = classifier.coef_[0]

            top_features = sorted(
                zip(feature_names, coefficients),
                key=lambda x: abs(x[1]),
                reverse=True
            )[:5]

            keywords = ", ".join([word for word, _ in top_features])

            st.markdown("### 🔍 Justification of Result")
            st.write(
                f"The prediction was influenced by high impact textual features such as: {keywords}."
            )
            st.write(
                f"The confidence score of {confidence * 100:.2f}% reflects the model’s certainty "
                "based on TF-IDF feature weighting and the learned Logistic Regression decision boundary."
            )

            st.caption(
                "This output represents a probabilistic assessment generated by an NLP model."
            )

            # ---------------- SAVE HISTORY ----------------
            st.session_state.history.append({
                "Time": datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
                "Text": text_input[:80] + "...",
                "Prediction": label,
                "Confidence (%)": round(confidence * 100, 2)
            })

# ---------------- DASHBOARD ----------------
with tab_dashboard:
    st.header("📊 Analysis Dashboard")

    if st.session_state.history:
        hist_df = pd.DataFrame(st.session_state.history)
        hist_df["Time"] = pd.to_datetime(hist_df["Time"])

        st.subheader("Prediction Distribution")
        st.bar_chart(hist_df["Prediction"].value_counts())

        st.subheader("Average Confidence Level")
        st.metric(
            "Mean Confidence",
            f"{hist_df['Confidence (%)'].mean():.2f}%"
        )

        st.subheader("Confidence Trend Over Time")
        st.line_chart(
            hist_df.set_index("Time")["Confidence (%)"]
        )
    else:
        st.info("No analysis data available yet.")

# ---------------- REPORTS ----------------
with tab_reports:
    st.header("📄 Reports")

    if st.session_state.history:
        report_df = pd.DataFrame(st.session_state.history)
        st.dataframe(report_df, use_container_width=True)

        csv = report_df.to_csv(index=False).encode("utf-8")
        st.download_button(
            "⬇️ Download CSV Report",
            csv,
            "fake_news_report.csv",
            "text/csv"
        )
    else:
        st.info("Run analysis to generate reports.")
